---
title: "git_01"
author: "Blanca Mares"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
“The sun was shining on the sea, Shining with all his might:

He did his very best to make

The billows smooth and bright-

And this was odd, because it was

The middle of the night."

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
O hushed October morning mild,

They leaves have ripened to the fall;

Tomorrow’s wind,if it be wild,

Should wastethem all.

The crows obove the forest call;

Tomorrow they may form and go.
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea, Shining with all his might:

He did his very best to make The billows smooth and bright And this was odd,

because it was The middle of the night.

The moon was shining sulkly, Because she thoght the sun Had got no business to be there

After the day was done ’It’s very rude of him, “she said”,

To come and spoil the funh

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
What is a dad

A dad is someone who wants to catch you before you fall

but instead picks you up, brushes you off,

And lets you try again.

A dad is someone who wants to keep you from making mistakes

but instead lets you find your own way,

even though his heart breaks in silence

when you get hurt,

A dad is someone who holdsyou when you cry,

Scolds you when you break the rules,

shines with pride when you succeed,

and has faith in you when you fall.
